language: kotlin

script:
  - curl "https://gist.githubusercontent.com/stefanbuck/ce788fee19ab6eb0b4447a85fc99f447/raw/dbadd7d310ce8446de89c4ffdf1db0b400d0f6c3/upload-github-release-asset.sh" > upload.sh
  - ./gradlew shadowJar
  - sh upload.sh martmists PokemonOverlay $(grep -Eo "'v.+'" build.gradle) build/libs/PokemonOverlay.jar $GIT_TOKEN

notifications:
  email: false