language: kotlin

install:
  - ./gradlew shadowJar

script:
  - sh upload.sh owner=martmists repo=PokemonOverlay tag=$(grep -Eo "'v.+'" build.gradle) filename=build/libs/PokemonOverlay.jar github_api_token=$GIT_TOKEN

notifications:
  email: false